### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by docssy** [aqariio/Fowl-Play#91]
### Version and loader

1.21.1 - Fabric

### Add a description

Hi,

As all entities have a performance cost, any plans to continue delivering more performance as your entities tick twice as hard as a minecraft bat. I'm heavily modded, but the birds I'm profiling with observable are 100us per.

Another bug, this jumps to 200us when there's some fish on the river floor that the birds can't reach as they start clumping together. Aggravated further when said fish is on a underwater magma block

**Comment by aqariio** [comment]
I'm currently focusing on improving and optimizing the ai for the various birds. The main problem lies in their complex behaviours, which is what causes the lag. This is very apparent when the birds spawn in, as you can see the tps drop significantly.

Unlike most vanilla mobs, the birds all use the brain ai system, which is used by newer mobs like the breeze, wardens, goats, frogs, etc. as well as villagers. The brain system is intrinsically more performance intensive compared to the goals ai system used by most mobs. 

There exists a mod called SmartBrainLib which optimizes and reworks the brain system. I am considering switching over to it due to the performance benefits that it offers, which will likely help with this issue.

> Another bug, this jumps to 200us when there's some fish on the river floor that the birds can't reach as they start clumping together. Aggravated further when said fish is on a underwater magma block

This issue should be fixed in the next update. If you find more problems with their pathfinding / behaviour, I would appreciate if you could list them here.

**Comment by obsidian29** [comment]
I'm going to put this here rather than opening a new issue, but I'm on 1.0.0, which apparently _is_ on SmartBrainLib, and I'm afraid I'm still absolutely choking on performance issues, and it feels even laggier than the previous version did.

I have observed TPS drops from all birds, but the worst culprits actually seem to be gulls. If there dare be gulls on the water, the lag is so immense I cannot play. I actually built an entire machine in creative mode the other day with command blocks and a redstone clock that killed birds, then killed all feather items, in a loop, just to be playable.

The thing is, most of the time, if a mod lagged this bad I'd pull it. But this is honestly one of my favorite mods. There's something so different about having the actual birdsong in the world, and it's only accentuated by the fact that one rarely actually sees a songbird. It makes the world feel alive in a way a soundscape never could. Right now I am bearing the lag, despite the fact that I've nearly died several times to Bird Lag, because I'd honestly rather have the birds.

Still, if this is anything that can be addressed, it would be deeply, deeply appreciated. Perhaps config options to decrease the complexity of bird behavior, so people can tweak how much they want complexity vs. performance. I'm honestly not pulling this mod unless I really have no choice, so if there's anything I can do to help, let me know.

Also, regarding bugs: On 1.0.0 for Fabric 1.20.1, I observed gulls "leaping" out of the water, not flying, just seemingly yeeting vertically about two blocks. I was lagging too hard to tell why, but it seemed like funky water physics. An entire flock of them resting on the water's surface was doing this. Don't know if there was a fish below them.

**Comment by aqariio** [comment]
I've optimized some parts of the birds' pathfinding, which should bring down their tps impact. I'll continue to work on optimizations in the future.

> I observed gulls "leaping" out of the water, not flying, just seemingly yeeting vertically about two blocks.

I've never seen this kind of behavior before. I'll do some testing, but it might have had something to do with your lag?

**Comment by aqariio** [comment]
The past few betas for 1.1.0 have offered several optimizations for bird pathfinding, which seemed to be the main culprit for the heavy tps impact. Of course, the brain still has a performance impact, typically raising the mspt by 2-3 in areas with lots of birds (80+) and probably more when the birds are doing something complex (like chasing a target). I'll continue to work on performance improvements, any feedback would be appreciated.

**Comment by italian-brainrot** [comment]
I have all bird weights set to 1, and still get insane lag sometimes, here is a spark report https://spark.lucko.me/6P1GC1fFRB

**Comment by aqariio** [comment]
I'll work on fixing this for the next update. Btw, I wouldn't recommend setting all spawn weights to one. The weights aren't the chance of a bird spawning, it represents the chance of a bird spawning relative to all other birds. Minecraft decides how many mobs to spawn based on a hardcoded number, and the weights just influence what percentage of all spawned birds is that one specific bird. Setting them all to one means that more resource intensive birds (like hawks or geese) will spawn more often.

**Comment by obsidian29** [comment]
If it helps, I've not had much lag lately. I no longer have access to the potato on which I suffered the intense performance issues, I am now on a _different_ potato, so I can't test that anymore. But on the other hand... unlaggy birds, so...

**Comment by TheDyllyDallier** [comment]
Hey noticed the latest update is quite laggy, I love this mod and would be ever grateful to be able to use it in my modpack without stuttering https://spark.lucko.me/c2UM5vMQSS

**Comment by aqariio** [comment]
Pathfinding optimization is a big priority for the next minor update (1.2.1), hopefully that'll finally result in better performance

**Comment by TheDyllyDallier** [comment]
I really hope so, because this is borderline unplayable and I really wish that wasn't the case... https://spark.lucko.me/9bgmh8aK5t

**Comment by Valokki** [comment]
Hi, for me performance in ocean biomes or Terrestria Volcanic Island biome is pretty bad with 1.2.0 version. Guls just keep spawning and soon you have over 200 birds and fps drops to single digits. Even before 100 birds performance hit Is quite bad, if you max out entity distance ocean is filled with seaguls. 

To be fair I have over 300 mods but after disabling fowl play game runs smooth at same location. On land there are not that much difference if Fowl play is on or off since bird count stays usually well under 50.

1.1.2 version guls didn't didn't spawn that fast and crazy amounts. I've been playing MC 1.20.1 version if that makes any difference.
